owner: aureooms
repo: monitor

sites:
  - name: Personal Homepage
    url: https://aurelienooms.be
  - name: Academic Homepage
    url: https://research.aurelienooms.be
  - name: Blog
    url: https://blog.aurelienooms.be
  - name: Math Blog
    url: https://math.aurelienooms.be

status-website:
  baseUrl: /monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor
  introTitle: "Public websites status monitor."
  introMessage: No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
